### ISSUE TITLE
Spurious buoyancy source from the immersed grid?

### ISSUE THREAD

**Issue by hdrake** [ikeshwani/HorizontalConvection#18]
@ikeshwani, you showed me some movies of 2D HC where it looks like there was a spurious buoyancy source where the ocean meets the immersed boundary just downstream of the hills.

@tomchor suggested these may be related to the fact that near the immersed grid, the ocean velocity is not perfectly non-divergent and, perhaps more importantly, there can be (small?) advective fluxes across the immersed grid even though the boundary condition is supposed to be $\mathbf{u} \cdot \mathbf{n} = 0$.

**Comment by hdrake** [comment]
@tomchor suggested that we check how sensitive these spurious buoyancy sources are to [a recent change in the code](https://github.com/CliMA/Oceananigans.jl/pull/3574) which in non-hydrostatic mode solves for the total pressure at all once, instead of separately finding the hydrostatic and non-hydrostatic components.

You can revert to the old behavior, in which the hydrostatic and non-hydrostatic pressures are separately evaluated, by changing this [keyword argument](https://github.com/CliMA/Oceananigans.jl/blob/406eb9c5c7a9fc86947747116128c8c1ba4c93d4/src/Models/NonhydrostaticModels/nonhydrostatic_model.jl#L70) when instantiating the `NonHydrostaticModel`. See the docstrings:

https://github.com/CliMA/Oceananigans.jl/blob/406eb9c5c7a9fc86947747116128c8c1ba4c93d4/src/Models/NonhydrostaticModels/nonhydrostatic_model.jl#L102-L106

**Comment by hdrake** [comment]
@ikeshwani, when you get the chance can you please upload the movies that show this bug (so we have a permanent record of them) and link to the git commit that corresponds with the settings in that simulation?

**Comment by ikeshwani** [comment]
Here's the original Ra=1e6 horizontal convection simulation:

https://github.com/user-attachments/assets/89c1d3f5-949e-402e-b02c-b64f3a8f2619

Here is the new Ra=1e6 simulation of horizontal convection where hydrostatic_pressure_anomaly = CenterField(grid) in the NonHydrostaticModel function. The bug seems to be fixed!

https://github.com/user-attachments/assets/df29ed0f-c35f-4311-a787-15e04afea882

**Comment by hdrake** [comment]
Nice work @ikeshwani! Can you create a new issue in the Oceananigans repository reporting this bug?

Key things to highlight:
- bug with immersed boundary when nonhydrostaric pressure is not separated
- explanation of the bug and what the intended behavior should be (default tracer flux boundary condition should be zero on immersed boundary)
- demonstration with your horizontal convection example movies with and without the pressure anomaly flag (give brief explanation of setup and link to your simulation setup script)

**Comment by tomchor** [comment]
Wow, look how different the simulation is in-between the mounts. Crazy! This makes me think that we should probably make the hydrostatic separation the default whenever `ImmersedBoundaryGrid`s are used.

Also as  note: I don't think necessary that the bug is _fixed_ when separating the pressure. Just that the effects of a divergent velocity are small enough to hopefully not meaningfully impact the solution. Really the way to fix it would be to have a pressure solver that properly accounts for immersed boundaries. I think that's what https://github.com/CliMA/Oceananigans.jl/pull/3188 aims to do.

**Comment by hdrake** [comment]
Yeah, I agree @tomchor. We'll need to do a careful domain-integrated buoyancy budget to know for sure.

**Comment by hdrake** [comment]
Following @tomchor's suggestion, @ikeshwani separated the hydrostatic pressure in [this commit](https://github.com/ikeshwani/HorizontalConvection/commit/d315803fa5c175c8a68f5c11cc2190ddb3b79905) and the [plots at the bottom of the notebook in this commit](https://github.com/ikeshwani/HorizontalConvection/blob/93830ccf9baf5787ddbf1085d13b85b86c4be630/notebooks/VariableRayleighAnalysis.ipynb) show that the spurious buoyancy source is removed.
