### ISSUE TITLE
Create function to calculate streamfunction

### ISSUE THREAD

**Issue by ikeshwani** [ikeshwani/HorizontalConvection#27]
$$ \frac{d\psi}{dz} = \int u dy = \Sigma u \Delta y $$

**Comment by hdrake** [comment]
Looks great!

<img width="1223" alt="Screenshot 2024-08-23 at 11 47 00 AM" src="https://github.com/user-attachments/assets/4ef90a8a-7577-4dc6-8916-403956c5fad3">

Two minor suggestions:
1) add a labelled colorbar
2) reverse the colors of the colorbar so that counterclockwise circulations are blue not red. This is more consistent with the oceanographic literature where the counterclockwise AABW cell is always blue.

From Lumpkin and Speer (2007)

<img width="797" alt="Screenshot 2024-08-23 at 11 49 13 AM" src="https://github.com/user-attachments/assets/e4570588-7cc6-4f37-a671-9a0bce8dce43">

**Comment by ikeshwani** [comment]
How does this look? @hdrake 

![download-22](https://github.com/user-attachments/assets/331b4661-5080-445a-8746-52425536b94a)

**Comment by hdrake** [comment]
Colors are a bit saturated but otherwise good! One trick is you can set the limits to `(-max(abs(psi)), +max(abs(psi))` to always be guaranteed a nice-looking heatmap that is centered around 0.

**Comment by hdrake** [comment]
Would also be nice to include some contours of buoyancy overlaid on top of the heatmap!

**Comment by ikeshwani** [comment]
![download-23](https://github.com/user-attachments/assets/9ffe7d6e-3238-483d-9f1b-5979f7019825)

Hmm.. not sure if this is much better

**Comment by hdrake** [comment]
Yeah, I think that helps. You can see the streamfunction is stronger near the bottom where the plume drops down to.

It also will probably help to make the aspect ratio of the plot closer to the aspect ratio of the domain (8 times longer than it is deep).
